server:
  id: springData
  port: 13001

spring:
  application:
    name: ${server.id}
  main:
    banner_mode: OFF
  datasource:
    url: jdbc:postgresql://postgres:5432/${server.id}
    username: admin
    password: admin
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
